CREATE TABLE AUTHORIZED_IPS (
    id SERIAL PRIMARY KEY,
    ip_address VARCHAR(50) NOT NULL
);

INSERT INTO AUTHORIZED_IPS (ip_address) VALUES ('127.0.0.1');
INSERT INTO AUTHORIZED_IPS (ip_address) VALUES ('0:0:0:0:0:0:0:1');
INSERT INTO AUTHORIZED_IPS (ip_address) VALUES ('192.168.1.100');


-- INSERT INTO ROLES (ID, NAME) VALUES (1, 'ADMIN');
-- INSERT INTO ROLES (ID, NAME) VALUES (2, 'GESTION');
--INSERT INTO ROLES (ID, NAME) VALUES (3, 'CONSULTA');

--INSERT INTO USERS (ID, USERNAME, PASSWORD) VALUES (1, 'admin', 'admin123');
--INSERT INTO USERS (ID, USERNAME, PASSWORD) VALUES (2, 'gestor1', 'gestor123');
--INSERT INTO USERS (ID, USERNAME, PASSWORD) VALUES (3, 'consulta1', 'consulta123');
--INSERT INTO USERS (ID, USERNAME, PASSWORD) VALUES (4, 'gestor2', 'gestor456');
--INSERT INTO USERS (ID, USERNAME, PASSWORD) VALUES (5, 'consulta2', 'consulta456');

-- admin -> ADMIN
--INSERT INTO USERS_ROLES (USER_ENTITY_ID, ROLES_ID) VALUES (1, 1);

-- gestor1 -> GESTION
--INSERT INTO USERS_ROLES (USER_ENTITY_ID, ROLES_ID) VALUES (2, 2);

-- consulta1 -> CONSULTA
--INSERT INTO USERS_ROLES (USER_ENTITY_ID, ROLES_ID) VALUES (3, 3);

-- gestor2 -> GESTION
--INSERT INTO USERS_ROLES (USER_ENTITY_ID, ROLES_ID) VALUES (4, 2);

-- consulta2 -> CONSULTA
--INSERT INTO USERS_ROLES (USER_ENTITY_ID, ROLES_ID) VALUES (5, 3);

